openapi: 3.0.4
info:
  title: Translator
  description: Translator is a simple tool for translating text. It returns the translated text.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/translator:
    post:
      summary: Translate Text
      description: Translator is a simple tool for translating text. It returns the translated text.
      operationId: translator
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  sourceLang: en
                  targetLang: es
                  translatedText: ¡Estoy tan emocionada porque mañana hará sol! ¡No puedo esperar!
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to translate
                  example: I'm so excited that tomorrow is going to be sunny! Can't wait!
                target:
                  type: string
                  description: The language code to translate the text to (e.g., fr)
                  example: es
                source:
                  type: string
                  description: The language code of the text to translate (e.g., en). If left blank, language will be auto-detected
                  example: en
              required:
              - text
              - target
              example:
                text: I'm so excited that tomorrow is going to be sunny! Can't wait!
                source: en
                target: es
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
